"""Framework-independent business rules for OperaMind."""

from operamind.domain.canonical_facts import (
    CanonicalFact,
    CanonicalFactMapper,
    CanonicalFieldEvidence,
    CanonicalMappingReason,
    CanonicalMappingResult,
    CanonicalMappingStatus,
    ObservedField,
    ObservedRecord,
)
from operamind.domain.code_scope import (
    CodeAnchor,
    CodeAnchorKind,
    CodeAnchorMatch,
    CodeGraphPath,
    CodeGraphTraversalPlanner,
    CodeRelationPolicy,
    CodeScopeEdge,
    CodeTraversalResult,
    relation_policy_for_domain,
)
from operamind.domain.command_execution import SafeCommandTemplate
from operamind.domain.document_nodes import (
    CanonicalDocumentNodeBuilder,
    DocumentNode,
    DocumentNodeType,
)
from operamind.domain.document_relations import (
    DocumentRelationFact,
    DocumentRelationPlan,
    DocumentRelationPlanner,
    DocumentRelationRule,
    PlannedDocumentRelation,
    RelationUnresolvedReason,
    RelationValueNormalizer,
    UnresolvedDocumentRelation,
)
from operamind.domain.rag import (
    DocumentEmbeddingInput,
    DocumentEmbeddingInputBuilder,
    SearchCandidate,
    SearchChannel,
)
from operamind.domain.rag_query_plan import (
    RagPlannedQuery,
    RagQueryPlan,
    RagQueryPurpose,
    StructuredChangeQueryPlanner,
)
from operamind.domain.structured_changes import (
    CanonicalSnapshot,
    ChangeConfidence,
    ChangeReviewStatus,
    ChangeType,
    FactState,
    SnapshotFact,
    StructuredChange,
    StructuredChangeBuilder,
)
from operamind.domain.ui_execution import (
    BrowserAction,
    BrowserActionKind,
    BrowserAssertion,
    BrowserAssertionKind,
    BrowserExecutionManifest,
    BrowserFailureCategory,
    BrowserLocator,
    BrowserScenarioSpec,
    BrowserValue,
    LocatorStrategy,
)
from operamind.domain.ui_knowledge import (
    UiKnowledgeSnapshot,
    UiKnowledgeTarget,
    UiLocatorCandidate,
)
from operamind.domain.ui_knowledge_proposal import (
    UiKnowledgeProposal,
    UiKnowledgeProposalBuilder,
    UiKnowledgeProposalIssue,
)
from operamind.domain.ui_runtime_observation import (
    UiLocatorObservationStatus,
    UiRuntimeLocatorObservation,
    UiRuntimeObservationEvidence,
    UiRuntimeObservationIssue,
    UiRuntimeObservationMerger,
    UiRuntimeObservationResult,
    runtime_candidate_id,
    runtime_observation_id,
)

__all__ = [
    "BrowserAction",
    "BrowserActionKind",
    "BrowserAssertion",
    "BrowserAssertionKind",
    "BrowserExecutionManifest",
    "BrowserFailureCategory",
    "BrowserLocator",
    "BrowserScenarioSpec",
    "BrowserValue",
    "CanonicalDocumentNodeBuilder",
    "CanonicalFact",
    "CanonicalFactMapper",
    "CanonicalFieldEvidence",
    "CanonicalMappingReason",
    "CanonicalMappingResult",
    "CanonicalMappingStatus",
    "CanonicalSnapshot",
    "ChangeConfidence",
    "ChangeReviewStatus",
    "ChangeType",
    "CodeAnchor",
    "CodeAnchorKind",
    "CodeAnchorMatch",
    "CodeGraphPath",
    "CodeGraphTraversalPlanner",
    "CodeRelationPolicy",
    "CodeScopeEdge",
    "CodeTraversalResult",
    "DocumentEmbeddingInput",
    "DocumentEmbeddingInputBuilder",
    "DocumentNode",
    "DocumentNodeType",
    "DocumentRelationFact",
    "DocumentRelationPlan",
    "DocumentRelationPlanner",
    "DocumentRelationRule",
    "FactState",
    "LocatorStrategy",
    "ObservedField",
    "ObservedRecord",
    "PlannedDocumentRelation",
    "RagPlannedQuery",
    "RagQueryPlan",
    "RagQueryPurpose",
    "RelationUnresolvedReason",
    "RelationValueNormalizer",
    "SafeCommandTemplate",
    "SearchCandidate",
    "SearchChannel",
    "SnapshotFact",
    "StructuredChange",
    "StructuredChangeBuilder",
    "StructuredChangeQueryPlanner",
    "UiKnowledgeProposal",
    "UiKnowledgeProposalBuilder",
    "UiKnowledgeProposalIssue",
    "UiKnowledgeSnapshot",
    "UiKnowledgeTarget",
    "UiLocatorCandidate",
    "UiLocatorObservationStatus",
    "UiRuntimeLocatorObservation",
    "UiRuntimeObservationEvidence",
    "UiRuntimeObservationIssue",
    "UiRuntimeObservationMerger",
    "UiRuntimeObservationResult",
    "UnresolvedDocumentRelation",
    "relation_policy_for_domain",
    "runtime_candidate_id",
    "runtime_observation_id",
]
